[[main]]
  name = "Home"
  url = ""
  weight = -110

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Projects"
  identifier = "Projects"
  weight = -109
[[main]]
  parent = "Projects"
  name = "Visual Green Tech"
  url = "https://sketchthedocs.dev/visual-green-tech/"
[[main]]
  parent = "Projects"
  name = "A-B-See"
  url = "https://sketchthedocs.dev/a-b-see/"
[[main]]
  parent = "Projects"
  name = "Visualize IT!"
  url = "https://aka.ms/visualize-it"

[[main]]
  name = "Archives"
  url = "post/rich-content/"
  weight = -108

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/sketchthedocs/"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/sketchthedocs"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/nityan"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"


# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"